//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB17Entities1 : DbContext
    {
        public DB17Entities1()
            : base("name=DB17Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<CartReport> CartReports { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Report1> Report1 { get; set; }
        public DbSet<tbl_invoice> tbl_invoice { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
    
        public virtual ObjectResult<CustomerOrder_Result> CustomerOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustomerOrder_Result>("CustomerOrder");
        }
    
        public virtual ObjectResult<ProductReport_Result> ProductReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductReport_Result>("ProductReport");
        }
    }
}
