//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.tbl_order = new HashSet<tbl_order>();
            this.tbl_order1 = new HashSet<tbl_order>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string ProductDescription { get; set; }
        public int ProductPrice { get; set; }
        public Nullable<int> ProductStatus { get; set; }
        public Nullable<int> ProdctFK_admin { get; set; }
        public Nullable<int> ProdctFK_customer { get; set; }
        public Nullable<int> ProdctFK_category { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<tbl_order> tbl_order { get; set; }
        public virtual ICollection<tbl_order> tbl_order1 { get; set; }
    }
}
